#!/usr/bin/env bash
# Configures a new Ubuntu machine

sudo apt -y update
sudo apt -y install nginx
ufw allow 'Nginx HTTP'
sudo echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart
