#!/usr/bin/env/ bash
# Script using while, if, elif and else to display

i=1
while [[ $i -le 10 ]]; do
	if (( i == 4 )); then
		echo "bad luck"
	elif (( i == 8 )); then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$((i + 1))
done
